Add background squares and refactor coloring system
Isaac-Lozano/rusty_chess_ai pull request #1
Opened 2017-02-08 06:41 UTC by Grognak

2017-02-08 07:09 UTC, Isaac-Lozano requested changes
Still need to restructure things to make it more Rusty, but looks good so far.

2017-02-08 07:09 UTC, Isaac-Lozano commented on src/chess_board.rs
> +                    print!("{}", color::gen_color_escape_code(color::FG_GREEN, is_white_space));
Need to decouple color functionality and board state. So remove the bool parameter to `color::gen_color_escape_code()` and add a background color as a second parameter.

2017-02-08 07:09 UTC, Isaac-Lozano commented on src/color.rs
> +pub const BG_WHITE: u32     = 47;
Make a Color enum and add these as elements, then add a `as_background_color(self) -> u32` and `as_foreground_color(self) -> u32` functions.

2017-02-08 07:09 UTC, Isaac-Lozano commented on src/color.rs
> +pub const BG_WHITE: u32     = 47;
We only need the colors themselves, and not if they're bg/fg, so something like:
```rust
pub enum Color
{
    Black,
    Red,
    Green,
    Yellow,
    Blue,
    Magenta,
    Cyan,
    White,
}
```

2017-02-08 07:09 UTC, Isaac-Lozano commented on src/color.rs
> +pub fn gen_color_escape_code(fgcolor: u32, is_white_space: bool) -> String
As mentioned before, change the function to:
```rust
pub fn gen_color_escape_code(fg: Color, bg: Color) -> String
{
    ...
}
```

2017-02-08 07:09 UTC, Isaac-Lozano commented on src/chess_board.rs
>                  print!("\x1b[0m");
Perhaps add a `gen_reset_color()` or something similar to color.rs to replace this line.

2017-02-09 08:29 UTC, Grognak commented
Ready for re-review

2017-02-09 22:48 UTC, Isaac-Lozano commented on src/color.rs
> +}
Tests should separated from other code by putting it in a module. Similar to tests in the minimax crate/repo.

2017-02-09 22:50 UTC, Isaac-Lozano approved these changes
It's all good except for tests being outside of a module. Also a bit of extra newlines after the end of the file but that's fine. You can submit another pull request to fix these if you want, but this will be accepted.

2017-02-09 22:50 UTC, merged